# Generated by Django 5.1.3 on 2024-11-06 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_rename_status_todo_completed_remove_book_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='task',
            new_name='title',
        ),
    ]
