# Generated by Django 5.1.3 on 2024-11-06 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_rename_task_todo_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='title',
            new_name='todo_title',
        ),
    ]
